# Generated by Django 4.0.2 on 2022-03-01 19:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_image_location_delete_editor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pic',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
